openapi: 3.0.3
info:
    title: Blank API
    version: 0.0.2
    description: This is a simple API descriptor.
paths:
    /files/{bucket_name}:
        get:
            tags:
                - File-Controller
            responses:
                "200":
                    $ref: "#/components/responses/BucketFileListResponse"
            operationId: list_monster_files
            summary: list_monster_files
        parameters:
            - name: bucket_name
              schema:
                  type: string
              in: path
              required: true
        x-openapi-router-controller: src.main.infraestructure.rest.Jump
    /files/{bucket_name}/{file_name}:
        post:
            tags:
                - File-Controller
            responses:
                "200":
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/MessageDto"
                    description: ok
                "500":
                    $ref: "#/components/responses/SimpleErrorResponse"
            operationId: insert_file
            summary: insert_file
        parameters:
            - name: bucket_name
              schema:
                  type: string
              in: path
              required: true
            - name: file_name
              schema:
                  type: string
              in: path
              required: true
        x-openapi-router-controller: src.main.infraestructure.rest.Jump
    /files/{bucket_name}/{file_name}/split:
        post:
            tags:
                - File-Controller
            parameters:
                - name: bucket_name
                  schema:
                      type: string
                  in: path
                  required: true
                - name: file_name
                  schema:
                      type: string
                  in: path
                  required: true
            responses:
                "200":
                    $ref: "#/components/responses/SimpleMessageResponse"
                "500":
                    $ref: "#/components/responses/SimpleErrorResponse"
            operationId: split_file
            summary: split_file
        x-openapi-router-controller: src.main.infraestructure.rest.Jump
    /yolo/{bucket_name}/{file_name}/train:
        post:
            tags:
                - YoloController
            responses:
                "200":
                    $ref: "#/components/responses/SimpleMessageResponse"
                "500":
                    $ref: "#/components/responses/SimpleErrorResponse"
            operationId: execute_yolo
            summary: execute_yolo
            description: execute_yolo
        parameters:
            - name: bucket_name
              schema:
                  type: string
              in: path
              required: true
            - name: file_name
              schema:
                  type: string
              in: path
              required: true
        x-openapi-router-controller: src.main.infraestructure.rest.Jump
    /yolo/{bucket_name}/detect/{file_name}:
        post:
            requestBody:
                description: DetectDto
                content:
                    application/json:
                        schema:
                            $ref: "#/components/schemas/DetectDto"
                required: true
            tags:
                - YoloController
            responses:
                "200":
                    $ref: "#/components/responses/SimpleMessageResponse"
                "500":
                    $ref: "#/components/responses/SimpleErrorResponse"
            operationId: execute_detect
            summary: execute_detect
            description: v
        parameters:
            - name: bucket_name
              schema:
                  type: string
              in: path
              required: true
            - name: file_name
              schema:
                  type: string
              in: path
              required: true
        x-openapi-router-controller: src.main.infraestructure.rest.Jump
    /yolo/{bucket_name}/detect/all:
        post:
            requestBody:
                content:
                    application/json:
                        schema:
                            $ref: "#/components/schemas/DetectDto"
                required: true
            tags:
                - YoloController
            parameters:
                - name: bucket_name
                  schema:
                      type: string
                  in: path
                  required: true
            responses:
                "200":
                    description: ok
                "400":
                    $ref: "#/components/responses/SimpleErrorResponse"
            operationId: execute_detect_all
            summary: execute detect all files in bucket
            description: execute detect all files in bucket
components:
    schemas:
        BucketFileListDto:
            description: ""
            required:
                - bucket
                - files_info
            type: object
            properties:
                bucket:
                    description: ""
                    type: string
                files_info:
                    description: ""
                    type: array
                    items:
                        $ref: "#/components/schemas/FileInfoStorageDto"
        FileInfoStorageDto:
            description: ""
            required:
                - file_name
                - file_size
                - unit
                - content_type
            type: object
            properties:
                file_name:
                    description: ""
                    type: string
                file_size:
                    format: int64
                    description: ""
                    type: integer
                unit:
                    description: ""
                    type: string
                content_type:
                    description: ""
                    type: string
        MessageDto:
            description: ""
            required:
                - message
            type: object
            properties:
                message:
                    description: ""
                    type: string
        ErrorDto:
            description: ""
            required:
                - error
            type: object
            properties:
                error:
                    description: ""
                    type: string
        DetectDto:
            description: ""
            type: object
            properties:
                show:
                    description: If True, displays the annotated images or videos in a window.
                        Useful for immediate visual feedback during development
                        or testing.
                    type: boolean
                save:
                    description: Enables saving of the annotated images or videos to files. Useful
                        for documentation, further analysis, or sharing results.
                        Defaults to True when using CLI & False when used in
                        Python.
                    type: boolean
                show_labels:
                    description: Displays labels for each detection in the visual output. Provides
                        immediate understanding of detected objects.
                    type: boolean
                show_boxes:
                    description: ""
                    type: boolean
    responses:
        BucketFileListResponse:
            content:
                application/json:
                    schema:
                        $ref: "#/components/schemas/BucketFileListDto"
            description: ""
        SimpleMessageResponse:
            content:
                application/json:
                    schema:
                        $ref: "#/components/schemas/MessageDto"
            description: ""
        SimpleErrorResponse:
            content:
                application/json:
                    schema:
                        $ref: "#/components/schemas/ErrorDto"
            description: ""
